### ISSUE TITLE
Travis not decrypting Artifactory username

### ISSUE THREAD

**Issue by jdcba** [CommBank/spectroscopy#10]
In branch `omnia-ci` 0265b38 I added the service account credentials for artifactoryonline. This parses and builds successfully:

https://travis-ci.com/CommBank/spectroscopy/builds/81732091#L422-L423

However when this was merged into `cdh-513` 376c3ab it no longer works, because the username is no longer decrypted:

https://travis-ci.com/CommBank/spectroscopy/builds/81731439#L419

**Comment by SamRoberts** [comment]
I think we've misdiagnosed this issue.

Take a look at https://travis-ci.com/CommBank/spectroscopy/requests: it shows a bunch of builds from the cdh-513 branch not running because the .travis.yml was malformed. Those "not running" builds never showed up anywhere else on the GUI and you can't find that page on the GUI unless you get linked directly to it.

The format error in question was caused by items in the env.global list appearing at different indentations.

Fixing the indentation in the .travis.yml file fixes the build, and allows us to publish to travis.
