### ISSUE TITLE
Travis integration is not working

### ISSUE THREAD

**Issue by jdcba** [CommBank/spectroscopy#9]
Sometime during Tue 14 Aug 2018, integration between github.com and travis-ci.com stopped working. Builds of modified branches are no longer triggering, Travis is not acknowledging new branches, and build statuses are not showing in github.com.

**Comment by SamRoberts** [comment]
I think we've misdiagnosed this issue.

Take a look at https://travis-ci.com/CommBank/spectroscopy/requests: it shows a bunch of builds from the cdh-513 branch not running because the .travis.yml was malformed. Those "not running" builds never showed up anywhere else on the GUI and you can't find that page on the GUI unless you get linked directly to it.

The format error in question was caused by items in the env.global list appearing at different indentations.

Fixing the indentation in the .travis.yml file fixes the build, and allows us to publish to travis.

**Comment by jdcba** [comment]
Aha, great sleuthing. Yes it seems there’s a defect in the Travis-CI web UI on this. Those new branches aren’t even acknowledged to exist, and for the existing branches there’s no link to the hidden history of failures.
